logging:
  level:
    org:
      hibernate:
        SQL: 'off'
        type:
          descriptor:
            sql:
              BasicBinder: 'off'
server:
  port: ${SOCIAL_SERVER_PORT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SOCIAL_DATABASE_PASSWORD}
    url: ${SOCIAL_DATABASE_URL}
    username: ${SOCIAL_DATABASE_USER}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: true
  ldap:
    password: ${SOCIAL_LDAP_PASSWORD}
    urls: ${SOCIAL_LDAP_URL}
    username: ${SOCIAL_LDAP_USERNAME}
