logging:
  level: 
    org:
      hibernate:
        SQL: off
        type: off
        cache: debug
server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Password111
    url: jdbc:postgresql://localhost:5432/SocialDB
    username: social
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:     
        show_sql: true
        format_sql: true
        generate_statistics: true
        cache:
          provider_class: org.hibernate.cache.EhCacheProvider
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
          use_query_cache: true
      javax:
        persistence:
          sharedCache:
            mode:ENABLE_SELECTIVE
  ldap:
    password: secret
    urls: ldap://localhost:10389/
    username: uid=admin, ou=system
vaadin:  servlet:    production-mode: true
    
folder:
  image: c:/Development/Java/Komolyabb/Komolyabb/images/
