logging:
  level: 
    org:
      hibernate:
        SQL: off
        type: off
      springframework:
        cache: trace
server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Password111
    url: jdbc:postgresql://localhost:5432/SocialDB
    username: social
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:     
        show_sql: true
        format_sql: true
        generate_statistics: true
  ldap:
    password: secret
    urls: ldap://localhost:10389/
    username: uid=admin, ou=system
  cache:
    ehcache:      config:
        classpath:ehcache.xml
vaadin:  servlet:    production-mode: true
    
folder:
  image: c:/Development/Java/Komolyabb/Komolyabb/images/
